[versions]
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.4"
uiTextGoogleFonts = "1.6.8"
coil = "2.7.0"
retrofit = "2.9.0"
okhttp = "4.9.3"

activityCompose = "1.9.0"
coilCompose = "2.6.0"
compose-bom = "2024.06.00"
core-ktx = "1.13.1"
hiltAndroid = "2.48"
hiltWork = "1.0.0"
androidxRuntime = "2.8.1"
hiltNavigationCompose = "1.2.0"
kotlin = "2.0.0"
lifecycleViewmodelCompose = "2.8.4"
androidApplication = "8.4.2"
ksp = "2.0.0-1.0.22"
kotlin-dsl = "4.4.0"
room = "2.5.0"
junitKtx = "1.2.1"
mokito = "4.11.0"
mokito-kotlin = "4.1.0"
mockk = "1.13.11"
ktx-coroutines-test = "1.6.4"
androidx-arch-core-test = "2.1.0"
androidx-test-core = "1.4.0"

paging-compose = "3.2.0"
paging = "3.2.0"


[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gjson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
okhhtp3 = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleViewmodelCompose" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltWork" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }
hilt-common = { module = "androidx.hilt:hilt-common", version.ref = "hiltWork" }
androidx-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidxRuntime" }
room-android = { module = "androidx.room:room-runtime", version.ref = "room"}
room-compiler-android = { module = "androidx.room:room-compiler", version.ref = "room"}
room-android-ktx = { module = "androidx.room:room-ktx", version.ref = "room"}
room-android-paging = { module = "androidx.room:room-paging", version.ref = "room"}

androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }

mockito-core = {group = "org.mockito",  name="mockito-core", version.ref = "mokito" }
mockito-kotlin = {module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mokito-kotlin" }
ktx-coroutines-test = {group = "org.jetbrains.kotlinx",  name="kotlinx-coroutines-test", version.ref = "ktx-coroutines-test" }
androidx-arch-core-test = {group = "androidx.arch.core",  name="core-testing", version.ref = "androidx-arch-core-test" }
androidx-test-core-test = {group = "androidx.test", name="core", version.ref = "androidx-test-core" }

androidx-paging-compose = {module = "androidx.paging:paging-compose", version.ref = "paging-compose"}
androidx-paging-runtime = {module = "androidx.paging:paging-runtime", version.ref = "paging"}
mockk = {module= "io.mockk:mockk", version.ref="mockk"}


[plugins]
android-application = { id = "com.android.application", version.ref = "androidApplication" }
android-library = { id = "com.android.library", version.ref = "androidApplication" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-dsl = { id = "org.gradle.kotlin.kotlin-dsl", version.ref = "kotlin-dsl" }
